
const privacy_policy = {
  title: "Privacy Policy",
  content: "Nomeo Realtors (hereinafter referred to as 'Nomeo') is committed to protecting the privacy of its clients (hereinafter referred to as 'Client'). This privacy policy outlines how Nomeo collects, uses, and discloses Client's personal information. Nomeo collects Client's personal information, such as name, contact details, and financial information, as necessary to provide its real estate services. Nomeo uses Client's personal information to facilitate property searches, negotiate transactions, and communicate with Client. Nomeo may disclose Client's personal information to third-party service providers, such as mortgage lenders and title companies, as necessary to fulfill its obligations. Nomeo takes reasonable measures to protect Client's personal information from unauthorized access, disclosure, or use. However, no method of transmission over the internet or electronic storage is completely secure. Nomeo may update this privacy policy from time to time. Any changes will be posted on Nomeo's website. By using Nomeo's services, Client consents to the collection, use, and disclosure of their personal information as described in this privacy policy."
};

const terms_and_conditions = {
  title: "Terms and Conditions",
  content: "Nomeo Realtors (hereinafter referred to as 'Nomeo') provides real estate services to its clients (hereinafter referred to as 'Client'). By engaging Nomeo's services, Client agrees to be bound by the following terms and conditions: Nomeo acts as an intermediary between Client and property owners. Nomeo is not a party to any property transaction and does not provide legal or financial advice. Client is responsible for conducting due diligence and seeking independent legal and financial counsel before entering into any agreement. Nomeo's commission is due upon the successful completion of a transaction, as outlined in the listing agreement. Client agrees to indemnify and hold Nomeo harmless from any claims, liabilities, or losses arising from Client's actions or representations. Nomeo reserves the right to terminate this agreement at any time for any reason. Client acknowledges that Nomeo may share Client's personal information with third-party service providers as necessary to fulfill its obligations. Nomeo is not responsible for any damages or losses incurred by Client as a result of the use of its services. These terms and conditions constitute the entire agreement between Client and Nomeo and supersede all prior or contemporaneous communications, representations, or agreements, whether oral or written. Any changes to these terms and conditions must be made in writing and signed by both parties."
};

const terms_of_service = {
  title: "Terms of Service",
  content: "Nomeo Realtors (hereinafter referred to as 'Nomeo') provides real estate services to its clients (hereinafter referred to as 'Client'). By engaging Nomeo's services, Client agrees to be bound by the following terms of service: Nomeo acts as an intermediary between Client and property owners. Nomeo is not a party to any property transaction and does not provide legal or financial advice. Client is responsible for conducting due diligence and seeking independent legal and financial counsel before entering into any agreement. Nomeo's commission is due upon the successful completion of a transaction, as outlined in the listing agreement. Client agrees to indemnify and hold Nomeo harmless from any claims, liabilities, or losses arising from Client's actions or representations. Nomeo reserves the right to terminate this agreement at any time for any reason. Client acknowledges that Nomeo may share Client's personal information with third-party service providers as necessary to fulfill its obligations. Nomeo is not responsible for any damages or losses incurred by Client as a result of the use of its services. These terms of service constitute the entire agreement between Client and Nomeo and supersede all prior or contemporaneous communications, representations, or agreements, whether oral or written. Any changes to these terms of service must be made in writing and signed by both parties."

};

const cookies_settings = {
  title: "Cookie Settings",
  content: "Nomeo Realtors (hereinafter referred to as 'Nomeo') uses cookies and similar technologies to enhance Client's experience on its website. Cookies are small text files that are stored on Client's device. Nomeo uses cookies to collect information about Client's usage of the website, such as pages visited, time spent, and preferences. This information is used to improve the website's content and functionality. Client can manage their cookie settings through their browser preferences. By continuing to use Nomeo's website, Client consents to the use of cookies as described in this policy."
};


export { privacy_policy, terms_and_conditions, terms_of_service, cookies_settings };
