export const blog_texts = {
  title: "Nomeo's Homefront Hub: Your Real Estate Inspiration Station",
  description: "Step into Nomeo's Homefront Hub, the vibrant blog of Nomeo Realtors, where Nigeria's real estate world comes alive! Here, we unpack everything from buying and renting apartments to mastering interior decoration and exploring investment opportunities. Whether you're a first-time homebuyer, a seasoned renter, or a design enthusiast seeking inspiration, our expert tips, market insights, and homeowner stories will guide your journey. Join our community, spark your ideas, and dive into the art and science of real estate with Nomeo Realtors—your next chapter starts here! Our carefully curated blog posts cover a diverse range of topics designed to empower your real estate decisions. From in-depth market analysis and property investment strategies to practical home maintenance tips and the latest interior design trends, each article is crafted by industry experts who understand the Nigerian real estate landscape. Discover success stories from satisfied clients, learn about emerging neighborhoods, get insider knowledge on property valuations, and stay updated with regulatory changes that affect property ownership. These blogs serve as your comprehensive resource, transforming complex real estate concepts into actionable insights that help you make informed decisions in your property journey.",
}

export const featured_blogs_text = {
  title: "Featured Blogs",
  description: "Explore the latest and most impactful articles from Nomeo's Homefront Hub. These blogs are carefully curated to provide you with valuable insights and practical tips for navigating the complex world of real estate in Nigeria. Whether you're a first-time homebuyer, a seasoned renter, or a design enthusiast seeking inspiration, our expert tips, market insights, and homeowner stories will guide your journey. Join our community, spark your ideas, and dive into the art and science of real estate with Nomeo Realtors—your next chapter starts here!",
}

export const featured_properties_text = {
  title: "Featured Properties",
  description: "Browse our featured listings below to get a glimpse of what we offer. From modern apartments in desirable neighborhoods to luxurious homes with stunning amenities, we're confident you'll find a property that captures your heart. Our diverse portfolio showcases premium properties across Nigeria's most sought-after locations, each carefully selected for their exceptional value, strategic positioning, and investment potential. Whether you're seeking a cozy starter home, a spacious family residence, or a high-end investment opportunity, our featured properties represent the finest in contemporary living and timeless elegance. Discover homes with state-of-the-art facilities, breathtaking views, and access to top-tier amenities including swimming pools, fitness centers, and 24/7 security. Each property listing comes with detailed specifications, professional photography, and comprehensive neighborhood insights to help you make informed decisions. From bustling city centers to serene suburban retreats, our featured properties cater to diverse lifestyles and budgets, ensuring that your dream home is just a click away"
}